---

- name: "local.yml | Pre-tasks"
  hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: "local.yml | Update apt package cache"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: False

- name: "local.yml | Roles"
  hosts: all
  become: true
  tasks:
    - name: "local.yml | Host specific roles"
      ansible.builtin.include_role:
        name: "{{ host_role.name | default(host_role) }}"
        tasks_from: '{{ host_role.tasks_from | default("main") }}'
        apply:
          tags:
            - '{{ host_role.name | default(host_role) }}'
      loop: '{{ host_roles }}'
      loop_control:
        loop_var: host_role
      tags:
        - always

- name: "local.yml | Post-tasks"
  hosts: all
  tags: always
  become: true
  tasks:
  - name: "local.yml | Clean up apt package cache"
    ansible.builtin.apt:
      autoclean: yes
    changed_when: false
