---

- name: "packages | desktop_apps | Install desktop app packages"
  tags: desktop_apps, packages
  ansible.builtin.apt:
    name:
      - "cmst"
      - "doublecmd-help-en"              # doublecmd-qt
      - "doublecmd-qt"
      - "keepassxc"
      - "libffmpegthumbnailer4v5"        # doublecmd-qt
      - "libunrar5"                      # doublecmd-qt
      - "mpv"
      - "putty"
      - "qalculate-gtk"
      - "qbittorrent"
      - "qdirstat"
      - "tigervnc-tools"
      - "tigervnc-viewer"
      - "translate-shell"
      - "yt-dlp"
      - "zbar-tools"
      - "zbarcam-qt"
    install_recommends: yes
    state: latest
