---

- name: "packages | desktop_apps | Install desktop app packages"
  tags: desktop_apps, packages
  ansible.builtin.apt:
    name:
      - "cmst"
      - "doublecmd-help-en"              # doublecmd-qt
      - "doublecmd-qt"
      - "keepassxc"
      - "libffmpegthumbnailer4v5"        # doublecmd-qt
      - "libunrar5"                      # doublecmd-qt
      - "mpv"
      - "putty"
      - "qalculate-gtk"
      - "qbittorrent"
      - "qdirstat"
      - "tigervnc-tools"
      - "tigervnc-viewer"
      - "translate-shell"
      - "yt-dlp"
      - "zbar-tools"
      - "zbarcam-qt"
    install_recommends: yes
    state: present

- name: "packages | desktop_apps | Install Sublime Text / Merge"
  tags: desktop_apps, packages
  block:
    - name: "packages | desktop_apps | Download and install the Sublime Text GPG key"
      ansible.builtin.get_url:
        url: "https://download.sublimetext.com/sublimehq-pub.gpg"
        dest: "/etc/apt/keyrings/sublimehq-pub.asc"
        owner: root
        group: root
        mode: "0644"

    - name: "packages | desktop_apps | Add the Sublime Text APT repository"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/sublimehq-pub.asc] https://download.sublimetext.com/ apt/stable/"
        filename: "sublime-text"
        mode: "0644"
        update_cache: true
        state: present

    - name: "packages | desktop_apps | Install Sublime Text & Sublime Merge"
      ansible.builtin.apt:
        name:
          - "sublime-merge"
          - "sublime-text"
        install_recommends: yes
        state: present

  rescue:
    - set_fact: task_failed=true

- name: "packages | desktop_apps | Install Beyond Compare"
  block:
    - name: "packages | desktop_apps | Setup Scooter Software's GPG key"
      ansible.builtin.copy:
        src: "files/system_setup/beyond_compare/scootersoftware-keyring.gpg"
        dest: "/usr/share/keyrings/scootersoftware-keyring.gpg"
        owner: root
        group: root
        mode: "0644"

    - name: "packages | desktop_apps | Setup the Scooter Software APT repository"
      ansible.builtin.copy:
        src: "files/system_setup/beyond_compare/scootersoftware.list"
        dest: "/etc/apt/sources.list.d/scootersoftware.list"
        owner: root
        group: root
        mode: "0644"

    - name: "packages | desktop_apps | Update apt package cache"
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      changed_when: False

    - name: "packages | desktop_apps | Install Beyond Compare"
      ansible.builtin.apt:
        name:
          - "bcompare"
        install_recommends: yes
        state: present

  rescue:
    - set_fact: task_failed=true

- name: "packages | desktop_apps | Install Microsoft Visual Studio Code"
  block:
    - name: "packages | desktop_apps | Download and install Microsoft's GPG key"
      ansible.builtin.get_url:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        dest: "/etc/apt/keyrings/microsoft.asc"
        owner: root
        group: root
        mode: "0644"

    - name: "packages | desktop_apps | Add the Visual Studio Code APT repository"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
        filename: "vscode"
        mode: "0644"
        update_cache: true
        state: present

    - name: "packages | desktop_apps | Install Microsoft Visual Studio Code"
      ansible.builtin.apt:
        name:
          - "code"
        install_recommends: yes
        state: present

  rescue:
    - set_fact: task_failed=true
