---

- name: "system_setup | environment | Configure a uniform look for applications"
  tags: environment, system_setup
  block:
    - name: "QT applications"
      ansible.builtin.blockinfile:
        path: "/etc/environment"
        create: true
        owner: root
        group: root
        mode: "0644"
        block: |
          # Some Java-based applications will display blank screen when
          # opened in a tiling WM. (e.g. JetBrains products)
          _JAVA_AWT_WM_NONREPARENTING=1

          # Disable automatic detection of DPI
          QT_AUTO_SCREEN_SCALE_FACTOR=0

          # Hardcode font DPI for QT apps
          QT_FONT_DPI=96

          # Disable QT debug logging to systemd journal
          QT_LOGGING_RULES="*.debug=false"

          # Make QT applications use the Kvantum style
          QT_STYLE_OVERRIDE="kvantum"
