---

# We keep track of what has been changed in new versions of Debian packages

- name: "system_setup | apt_listchanges | Configure apt-listchanges 1/3"
  tags: apt_listchanges, system_setup
  ansible.builtin.copy:
    dest: "/etc/apt/listchanges.conf.d/apt.conf"
    content: |
      [apt]
      frontend=log
      which=both
      email_address=root
      email_format=text
      confirm=false
      headers=false
      reverse=false
      titled=false
      save_seen=/var/lib/apt/listchanges.db
    owner: root
    group: root
    mode: "0644"

- name: "system_setup | apt_listchanges | Configure apt-listchanges 2/3"
  tags: apt_listchanges, system_setup
  ansible.builtin.copy:
    dest: "/etc/apt/listchanges.conf.d/cmdline.conf"
    content: |
      [cmdline]
      frontend=log
      which=both
      email_address=root
      email_format=text
      confirm=false
      headers=false
      reverse=false
      titled=false
      save_seen=/var/lib/apt/listchanges.db
    owner: root
    group: root
    mode: "0644"

- name: "system_setup | apt_listchanges | Configure apt-listchanges 3/3"
  tags: apt_listchanges, system_setup
  ansible.builtin.copy:
    src: "files/system_setup/apt_listchanges/logrotate"
    dest: "/etc/logrotate.d/apt_listchanges"
    owner: root
    group: root
    mode: "0644"
