---

- name: "hyperv_vm | Ensure Hyper-v guest packages are at their latest versions"
  tags: hyperv_vm
  ansible.builtin.apt:
    name:
      - "hyperv-daemons"
    install_recommends: yes
    state: latest
  when: ansible_distribution in ["Debian"]
